### ISSUE TITLE
Login problem on release.

### ISSUE THREAD

**Issue by altayhunoglu** [AppLozic/Applozic-Flutter-Plugin#1]
Hello,
I am testing on Android devices.

I can login on debug mode.

But, even if I have already purchased a "STARTER" plan, I cannot log in on release mode.
I get this exception message but it is not informative enough:
I use correct applicationId..

PlatformException(Error, {"detailMessage":"userId cannot be empty","stackTrace":[{"declaringClass":"b.b.a.a.a.a.a","fileName":"","lineNumber":87,"methodName":"a"},{"declaringClass":"b.b.a.a.a.b.j","fileName":"","lineNumber":2,"methodName":"a"},{"declaringClass":"b.b.a.a.a.b.j","fileName":"","lineNumber":1,"methodName":"doInBackground"},{"declaringClass":"android.os.AsyncTask$2","fileName":"AsyncTask.java","lineNumber":295,"methodName":"call"},{"declaringClass":"java.util.concurrent.FutureTask","fileName":"FutureTask.java","lineNumber":237,"methodName":"run"},{"declaringClass":"android.os.AsyncTask$SerialExecutor$1","fileName":"AsyncTask.java","lineNumber":234,"methodName":"run"},{"declaringClass":"java.util.concurrent.ThreadPoolExecutor","fileName":"ThreadPoolExecutor.java","lineNumber":1113,"methodName":"runWorker"},{"declaringClass":"java.util.concurrent.ThreadPoolExecutor$Worker","fileName":"ThreadPoolExecutor.java","lineNumber":588,"methodName":"run"},{"declaringClass":"java.lang.Thread","fileName":"Thread.java","lineNumber":818,"methodName":"run"}],"suppressedExceptions":[]}, null)

**Comment by reytum** [comment]
@altayhunoglu you need to enable proguard for Android.  Add the below rules in your proguard-rules.pro file: https://docs.applozic.com/docs/android-chat-sdk#proguard-setup

**Comment by altayhunoglu** [comment]
Hi Ashish,

You are right. Now, we can log in on release mode too.

It is why I close the issue.

Thanks for your attention.
